//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyDinhKhac
    {
        public int MaQuyDinh { get; set; }
        public string TenQuyDinh { get; set; }
        public int GiaTri { get; set; }
        public string GhiChu { get; set; }
    }
}
